import 'dotenv/config';

export const config = {
  PORT: process.env.PORT,
  NODE_ENV: process.env.NODE_ENV,
  APP_BACKEND_PREFIX: process.env.APP_BACKEND_PREFIX,

  FAST_POST_AWS_REGION: process.env.FAST_POST_AWS_REGION,

  KAFKA_CLIENT_TIMEOUT: process.env.KAFKA_CLIENT_TIMEOUT,

  IRYS_KAFKA_TOPIC: process.env.IRYS_KAFKA_TOPIC,
  FAST_POST_KAFKA_TOPIC: process.env.FAST_POST_KAFKA_TOPIC,

  IRYS_KAFKA_BROKER: process.env.IRYS_KAFKA_BROKER,
  FAST_POST_KAFKA_BROKER: process.env.FAST_POST_KAFKA_BROKER,

  LISTENER_CONSUMER_GROUP_ID: process.env.LISTENER_CONSUMER_GROUP_ID,
  LISTENER_CONSUMER_CLIENT_ID: process.env.LISTENER_CONSUMER_CLIENT_ID,

  LISTENER_PRODUCER_GROUP_ID: process.env.LISTENER_PRODUCER_GROUP_ID,
  LISTENER_PRODUCER_CLIENT_ID: process.env.LISTENER_PRODUCER_CLIENT_ID,

  NOTIFICATION_CONSUMER_GROUP_ID: process.env.NOTIFICATION_CONSUMER_GROUP_ID,
  NOTIFICATION_CONSUMER_CLIENT_ID: process.env.NOTIFICATION_CONSUMER_CLIENT_ID,

  NOTIFICATION_PRODUCER_GROUP_ID: process.env.NOTIFICATION_PRODUCER_GROUP_ID,
  NOTIFICATION_PRODUCER_CLIENT_ID: process.env.NOTIFICATION_PRODUCER_CLIENT_ID,

  SASL_USERNAME: process.env.SASL_USERNAME,
  SASL_PASSWORD: process.env.SASL_PASSWORD,

  SASL_ACCESS_KEY_ID: process.env.SASL_ACCESS_KEY_ID,
  SASL_SECRET_ACCESS_KEY: process.env.SASL_SECRET_ACCESS_KEY,
  SASL_AUTHORIZATION_IDENTITY: process.env.SASL_AUTHORIZATION_IDENTITY,

  SXT_API_KEY: process.env.SXT_API_KEY,
  SXT_AUTH_BASE_URL: process.env.SXT_AUTH_BASE_URL,
  SXT_API_BASE_URL: process.env.SXT_API_BASE_URL,
};
