import 'dotenv/config';

export const config = {
  PORT: process.env.PORT,
  NODE_ENV: process.env.NODE_ENV,
  APP_BACKEND_PREFIX: process.env.APP_BACKEND_PREFIX,

  AWS_REGION: process.env.AWS_REGION,

  IRYS_KAFKA_TOPIC: process.env.IRYS_KAFKA_TOPIC,
  FAST_POST_KAFKA_TOPIC: process.env.FAST_POST_KAFKA_TOPIC,

  IRYS_KAFKA_BROKER: process.env.IRYS_KAFKA_BROKER,
  FAST_POST_KAFKA_BROKER: process.env.FAST_POST_KAFKA_BROKER,

  KAFKA_CLIENT_TIMEOUT: process.env.KAFKA_CLIENT_TIMEOUT,

  LISTENER_CONSUMER_GROUP_ID: process.env.LISTENER_CONSUMER_GROUP_ID,
  LISTENER_CONSUMER_CLIENT_ID: process.env.LISTENER_CONSUMER_CLIENT_ID,

  LISTENER_PRODUCER_GROUP_ID: process.env.LISTENER_PRODUCER_GROUP_ID,
  LISTENER_PRODUCER_CLIENT_ID: process.env.LISTENER_PRODUCER_CLIENT_ID,

  SASL_USERNAME: process.env.SASL_USERNAME,
  SASL_PASSWORD: process.env.SASL_PASSWORD,

  SASL_ACCESS_KEY_ID: process.env.SASL_ACCESS_KEY_ID,
  SASL_SECRET_ACCESS_KEY: process.env.SASL_SECRET_ACCESS_KEY,
  SASL_AUTHORIZATION_IDENTITY: process.env.SASL_AUTHORIZATION_IDENTITY,

  PRODUCER_API_BASE_URL: process.env.PRODUCER_API_BASE_URL,
  PRODUCER_API_SINGLE_FILE_UPLOAD_ENDPOINT:
    process.env.PRODUCER_API_SINGLE_FILE_UPLOAD_ENDPOINT,

  WEBSOCKET_CONNECTION_URL: process.env.WEBSOCKET_CONNECTION_URL,
  WEBSOCKET_CONNECTION_TOKEN: process.env.WEBSOCKET_CONNECTION_TOKEN,

  SXT_API_KEY: process.env.SXT_API_KEY,

  SXT_API_DQL_PATH: process.env.SXT_API_DQL_PATH,
  SXT_API_DML_PATH: process.env.SXT_API_DML_PATH,
  SXT_API_DDL_PATH: process.env.SXT_API_DDL_PATH,

  SXT_AUTH_BASE_URL: process.env.SXT_AUTH_BASE_URL,
  SXT_API_TOKEN_REFRESH_URL: process.env.SXT_API_TOKEN_REFRESH_URL,

  SXT_API_BASE_URL: process.env.SXT_API_BASE_URL,

  QUERY_TYPE: process.env.QUERY_TYPE,

  /*------------
    FAST_POST
  ------------*/

  INBOUND_KAFKA_ACCOUNTING_JOURNAL_RESOURCE_ID:
    process.env.INBOUND_KAFKA_ACCOUNTING_JOURNAL_RESOURCE_ID,
  INBOUND_KAFKA_ACCOUNTING_JOURNAL_BISCUIT_TOKEN:
    process.env.INBOUND_KAFKA_ACCOUNTING_JOURNAL_BISCUIT_TOKEN,

  ACCOUNTING_JOURNAL_HEADER_RESOURCE_ID:
    process.env.ACCOUNTING_JOURNAL_HEADER_RESOURCE_ID,
  ACCOUNTING_JOURNAL_HEADER_BISCUIT_TOKEN:
    process.env.ACCOUNTING_JOURNAL_HEADER_BISCUIT_TOKEN,

  ACCOUNTING_JOURNAL_LINE_RESOURCE_ID:
    process.env.ACCOUNTING_JOURNAL_LINE_RESOURCE_ID,
  ACCOUNTING_JOURNAL_LINE_BISCUIT_TOKEN:
    process.env.ACCOUNTING_JOURNAL_LINE_BISCUIT_TOKEN,

  GL_EXTRACT_RESOURCE_ID: process.env.GL_EXTRACT_RESOURCE_ID,
  GL_EXTRACT_BISCUIT_TOKEN: process.env.GL_EXTRACT_BISCUIT_TOKEN,

  /*----------------
    ESB INTEGRATORS
  ----------------*/

  ESB_INTEGRATORS_RESOURCE_ID: process.env.ESB_INTEGRATORS_RESOURCE_ID,
  ESB_INTEGRATORS_BISCUIT_TOKEN: process.env.ESB_INTEGRATORS_BISCUIT_TOKEN,

  ESB_EVENTS_RESOURCE_ID: process.env.ESB_EVENTS_RESOURCE_ID,
  ESB_EVENTS_BISCUIT_TOKEN: process.env.ESB_EVENTS_BISCUIT_TOKEN,

  ESB_EVENT_MESSAGES_RESOURCE_ID: process.env.ESB_EVENT_MESSAGES_RESOURCE_ID,
  ESB_EVENT_MESSAGES_BISCUIT_TOKEN:
    process.env.ESB_EVENT_MESSAGES_BISCUIT_TOKEN,

  ESB_EVENT_METADATA_RESOURCE_ID: process.env.ESB_EVENT_METADATA_RESOURCE_ID,
  ESB_EVENT_METADATA_BISCUIT_TOKEN:
    process.env.ESB_EVENT_METADATA_BISCUIT_TOKEN,

  ESB_EVENT_ERRORS_RESOURCE_ID: process.env.ESB_EVENT_ERRORS_RESOURCE_ID,
  ESB_EVENT_ERRORS_BISCUIT_TOKEN: process.env.ESB_EVENT_ERRORS_BISCUIT_TOKEN,

  ESB_RAG_AI_BACKEND_URL: process.env.ESB_RAG_AI_BACKEND_URL
};
